### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dczwardCZAR** [p4535992/foundryvtt-variant-encumbrance-dnd5e#10]
**Module Version:** v0.11.11

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

**Describe the bug**
"Bulk" values do not "stick" to items after updating "bulk" in a second and subsequent item.

**To Reproduce**

- settings per screenshots below
- Open a character, go to inventory
- open an item, change the "Bulk" field from 0 to another amount.
- close and open the char sheet, the items shows the new bulk, and the bulk bar is updated correctly.
- open a second inventory item, and change the bulk amount from 0 to amount.
- close and re-open the character sheet
- see that both items show a bulk value of 0, and the bulk bar is at 0.

**Expected behavior**
- I expected the bulk values to remain/be saved for the changed inventory items, and the bulk bar to update accordingly.
- 
**Screenshots**
example, see the "Net", change bulk to 1. It worked.
see the shield +1, changed to 2, the error occurs.

<img width="556" alt="Screenshot 2023-01-27 at 9 01 49 AM" src="https://user-images.githubusercontent.com/91574640/215121187-549ef2a9-b44c-46ad-b235-a639cac22dc7.png">
<img width="554" alt="Screenshot 2023-01-27 at 9 02 33 AM" src="https://user-images.githubusercontent.com/91574640/215121189-f76479a8-fac6-4356-b4ee-4c7300d229da.png">
<img width="719" alt="Screenshot 2023-01-27 at 9 02 53 AM" src="https://user-images.githubusercontent.com/91574640/215121190-f8412eec-b6ff-4df0-9578-4fccb1678366.png">
<img width="720" alt="Screenshot 2023-01-27 at 9 03 10 AM" src="https://user-images.githubusercontent.com/91574640/215121191-aff4c7dc-5d8b-4127-951b-2ded32d13eec.png">
<img width="552" alt="Screenshot 2023-01-27 at 9 03 26 AM" src="https://user-images.githubusercontent.com/91574640/215121195-eb363866-77d1-4f0f-a4e2-17b005d53a6b.png">
<img width="553" alt="Screenshot 2023-01-27 at 9 03 45 AM" src="https://user-images.githubusercontent.com/91574640/215121200-1b540a79-2e9c-4b6e-9176-e596ec5323b5.png">
<img width="719" alt="Screenshot 2023-01-27 at 9 03 56 AM" src="https://user-images.githubusercontent.com/91574640/215121202-ecbe540e-081e-41cb-8f54-9ea344472229.png">
<img width="721" alt="Screenshot 2023-01-27 at 9 04 14 AM" src="https://user-images.githubusercontent.com/91574640/215121203-c58b8412-ec28-4698-917e-6e3b1cc844a3.png">

**Browser:**
Chrome Version 109.0.5414.119 (Official Build) (arm64)

**Foundry Version:** 
v10.291

**Game System:** 
DnD5e - Fifth Edition System v2.1.4

**Additional context**
tested with only the mod & dependencies enabled
Default DnD5e character sheet.

<img width="756" alt="Screenshot 2023-01-27 at 9 09 52 AM" src="https://user-images.githubusercontent.com/91574640/215119795-db6b5af8-81d1-40b8-99aa-7f8a162b4b27.png">
<img width="753" alt="Screenshot 2023-01-27 at 9 10 11 AM" src="https://user-images.githubusercontent.com/91574640/215119798-e991e1d4-b9b4-412c-9679-d888ecc09c46.png">
<img width="753" alt="Screenshot 2023-01-27 at 9 10 25 AM" src="https://user-images.githubusercontent.com/91574640/215119801-47404243-d1aa-4663-a43f-9e9a114f7d11.png">
<img width="748" alt="Screenshot 2023-01-27 at 9 10 37 AM" src="https://user-images.githubusercontent.com/91574640/215119805-f52184b8-24a8-4498-9e1c-ee5f5ead77cc.png">

[variant-enc-debug-log.txt](https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/files/10520123/variant-enc-debug-log.txt)

**Comment by p4535992** [comment]
Should be fixed with 0.12.1 try and let me know it
