### ISSUE TITLE
[BUG] Equipped Armor Multiplier doesn't work.

### ISSUE THREAD

**Issue by arlosmolten** [p4535992/foundryvtt-variant-encumbrance-dnd5e#11]
**Module Version:** v0.11.11

The homebrew "Feature: Equipped Armor Weight Multiplier" doesn't work. The multipliers are ignored, and all equipped weights become zeros. 

Trying with foundry v10.291, D&D5e 2.0.3, in a brand new world, creating a new actor, dragging an srd cloth and armor item, and trying to equip. Doesn't appear to be any kind of error in the console.

All images below for configuration, behavior, and console show the issue.

Configuration
(As a side note, the naming of the settings are wrong too, because all settings are only for clothing, and I think probably should be clothing, light, medium, heavy and natural)
![debug3](https://user-images.githubusercontent.com/64532901/215346056-1168cbe7-d780-4570-aec7-e3b227f6504d.png)

Testing
![debug2](https://user-images.githubusercontent.com/64532901/215346084-6b7a2e20-a763-42fb-b793-e22a317074c5.png)

Console
![debug](https://user-images.githubusercontent.com/64532901/215346090-4cad199b-c81b-497c-8658-42f75f39ffff.png)

**Comment by LtDerek** [comment]
Came to echo that I have the same problem.

**Comment by p4535992** [comment]
Try out 0.12.3 and let me know it

**Comment by arlosmolten** [comment]
Looks like is working as intended now. I think this issue can be closed now. Thanks.
