### ISSUE TITLE
[BUG] Currency does not apply effects, and items sometimes do not too.

### ISSUE THREAD

**Issue by Nedrapter** [p4535992/foundryvtt-variant-encumbrance-dnd5e#12]
**Module Version:** 0.11.11

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

**Describe the bug**
1)Currency weight does not apply any of the effects on the character.
2) Sometimes effects do not apply from item weight as well. 

**To Reproduce**
Change amount of currency and observe.

**Expected behavior**
Currency should apply the effects and item effects should be consistent.

**Screenshots**
Uploaded a gif here https://easyupload.io/8q5cly

**Browser:**
Opera GX and Firefox.

**Foundry Version:** 
10.291
**Game System:** 
dnd 5e 2.03
**Additional context**

No errors on the console.

**Comment by p4535992** [comment]
Should e fixed with 0.12.1, try out and let me know it
