### ISSUE TITLE
[BUG] v0.12.0 Doesn't update in real time anymore with equipped weight modifier

### ISSUE THREAD

**Issue by GambetTV** [p4535992/foundryvtt-variant-encumbrance-dnd5e#13]
**Module Version:** v0.12.0

I'm using the option to decrease the weight of equipped items, set to 0.5. When I equip and unequip an item, it does not update in sync anymore, and seems to skip a step or two, so I wind up having to equip/unequip the same item multiple times for the item to register its encumbrance value. The WEIGHT will update in real time, however the Encumbrance Effect seems to only update every other time I equip/unequip it.

**Comment by p4535992** [comment]
can you try with "0,5" instead "0.5" ?

**Comment by GambetTV** [comment]
I'm American. It doesn't even offer that as an option for me.

**Comment by p4535992** [comment]
Try out 0.12.3 and let me know it, if the issue persist

**Comment by marceloabner** [comment]
Looks like is working as intended now. Thanks.

**Comment by GambetTV** [comment]
Not sure about 12.3, but as of 12.4 it still doesn't work.
