### ISSUE TITLE
[Bugs(?) and Requests]  Allowing containers to reduce effective weight

### ISSUE THREAD

**Issue by JackaldaJester** [p4535992/foundryvtt-variant-encumbrance-dnd5e#14]
Hello! A couple of features I'd like to discuss...

1) Un-equipping a bag from Item Collection does not drop the weight to zero. I don't have the Item Collections setting enabled in the Variant Encumbrance settings (the one that says I DON'T RECOMMEND IT)

2) Unsure if this is a bug or not. "Equipped Item Weight Multiplier" only effects equipped weapons and armor, and nothing else. I think this may be intended and if so...

3) My intention is to allow bags and containers to reduce weight by a certain amount in order to incentivize players using bags and dealing with the hassle of encumbrance. It would be nice if there was a homebrew setting that allowed EQUIPPED bags or containers to reduce weight. 

Thank you!

**Comment by p4535992** [comment]
1 and 2 are a bug, 3 is a feature, i add a new module settings for manage that.
Try out 0.12.6

**Comment by JackaldaJester** [comment]
Working fantastic! Thank you very much for your hard work!
