### ISSUE TITLE
Speed penalties only applied on every other activation.

### ISSUE THREAD

**Issue by McShaker** [p4535992/foundryvtt-variant-encumbrance-dnd5e#15]
v 0.12.7
I am using default setttings.

Speed penalty calculations are only applied automatically every other activation.

Steps to reproduce.
1. add "chain mail" to inventory = result speed unchanged(30).
2. equip "chain mail" = result speed unchanged(30).
3. unequip "chain mail" = result speed changed(20).
4. equip "chain mail" = result speed unchanged(20).
5. unequip "chain mail" = result speed unchanged(20).
6. equip "chain mail" = result speed changed(30).
7. unequip "chain mail" = result speed unchanged(30).
8. loop to step 2

**Comment by p4535992** [comment]
Try out 0.12.8
