### ISSUE TITLE
Equipped Items are weightless even though homebrew rule is toggled off

### ISSUE THREAD

**Issue by KellethDregar** [p4535992/foundryvtt-variant-encumbrance-dnd5e#16]
The item weight is being ignored when an item is equipped even though the homebrew rule is disabled.

![image](https://user-images.githubusercontent.com/79947702/226231010-6d2c728e-42f9-4eda-8680-f92e14f2da3a.png)

armor equipped:
![image](https://user-images.githubusercontent.com/79947702/226231065-bfc3ae7f-0efe-4670-bfeb-1e98e6aad3ce.png)

armor unequipped:
![image](https://user-images.githubusercontent.com/79947702/226231088-156f76a6-27f3-4b6f-9255-d32a57691e61.png)

**Comment by p4535992** [comment]
Any chance the module setting "Equipped Item Weight Multiplier" is set to 0 ?

**Comment by p4535992** [comment]
nevermind, i see the issue now....

**Comment by p4535992** [comment]
should be fixed on 0.12.9
