### ISSUE TITLE
Currency in the bulk system

### ISSUE THREAD

**Issue by dczwardCZAR** [p4535992/foundryvtt-variant-encumbrance-dnd5e#17]
In an all bulk/item slots system, currency does not apply to the bulk system. Is it possible to have currency apply to the bulk system? i.e., 100 coins = 1 slot?

<img width="546" alt="Screenshot 2023-03-27 at 11 48 15 PM" src="https://user-images.githubusercontent.com/91574640/228131115-8f8da1f3-79ba-4244-acc1-19337785b633.png">

**Comment by p4535992** [comment]
Added a new module setting on 0.13.4
