### ISSUE TITLE
Use containers bulk, not items in containers bulk

### ISSUE THREAD

**Issue by Orionox** [p4535992/foundryvtt-variant-encumbrance-dnd5e#2]
So currently it appears that if you're using the bulk variant with the module item containers, containers will be counted as the same bulk as the item placed inside the container instead of the bulk of the actual container. I would like it if there was an option to allow the bulk of a container to override the bulk of items placed inside the container.

So I can have 10 bulk placed in a 3 bulk container, and my character sheet will only count the 3 bulk. I personally do this to encourage my players to spend money on different containers like quivers, and potion pouches... etc

Edit: Also an option to reduce the bulk of worn armor/clothing to 0 would be nice, bt is easy enough to do manually.

**Comment by p4535992** [comment]
What did you mean with _Also an option to reduce the bulk of worn armor/clothing to 0 would be nice, bt is easy enough to do manually._ ? You mean for equipped items to set bulk to 0 ?

**Comment by Orionox** [comment]
No, just clothing/armor since you don't really have to "hold" it so it doesn't really take up space. In fact most clothing makes it a little easier to hold items since clothing has like pockets and belts.

**Comment by Orionox** [comment]
Moved away from using item containers since you inventory + module fulfills my needs better

**Comment by p4535992** [comment]
@Orionox  the bug fix and the feature request are done on 0.11.4
