### ISSUE TITLE
ItemCollection/Item Container feature not working with Foundry v11

### ISSUE THREAD

**Issue by Amd321** [p4535992/foundryvtt-variant-encumbrance-dnd5e#22]
**Module Version:** v0.13.1

**Describe the bug**
The option "Use equipped/unequipped feature of the ItemCollection/ItemContainer modules for the backpack" which gives compatibility with the Itemcollection/Item Container module by Tim Posney, is not functioning. When Variant Encumbrance + Weight is enabled on a sheet, unequipping a backpack made with Tim Posney's Item Container module (set to Weightless Unequipped), does not lessen the inventory weight, and the encumbrance Active Effect is not removed.

**To Reproduce**
1. Check the box for "Use equipped/unequipped feature of the ItemCollection/ItemContainer modules for the backpack" in "Variant Encumbrance+midi for dnd5e" settings.
2. Enable "Variant Encumbrance + Weight" for character sheet
3. Create a container that has a weight above 0 in the character sheet and set it to "Weightless Encumbrance"
4. Add items with weight to character sheet until it just becomes encumbered, and the "Encumbered" Active Effect is added. 
5. Unequip backpack
6. Weight is not lessened, nor is "Encumbered" Active Effect removed.

**Expected behavior**
It is expected that when unequipping the backpack, the weight will be lessened, and the "Encumbered" active effect will be removed.

**Browser:**
 Firefox 115.0.3 (64-bit)

**Foundry Version:** Version 11 Stable, 11.306

**Game System:** dnd5e, 2.2.2

**Additional context**
A container's "Weightless Encumbrance" feature of Tim Posney's module functions fine when the character sheet is set to "Disabled VE + WE", however the Variant Encumbrance function of adding and removing the "Encumbered" Active effect does not work still.

Also, this was tested with newest builds of "Variant Encumbrance+midi for dnd5e", "Itemcollection/Item Container", "Dynamic Active Effects using After Effects" and their dependencies, as the only modules active.

**Comment by p4535992** [comment]
Should be fixed with 0.13.3 let me know it

**Comment by Amd321** [comment]
It's even more screwed up now. Removing a bag will remove encumbrance, but you can't re-equip the bag, and now the VE + WE swap icon on the top of a character sheet is not functioning properly. The equip function of bags are super wonky now, and don't toggle correctly.

**Comment by Dyrnwyrm** [comment]
Same issue here, also for some reason the actives aura are visible when the module is active for some reason that i cant figure it out

**Comment by p4535992** [comment]
~~Did you have any erorr on the web console ?~~ Nevermind i see the error... try out 0.13.5

**Comment by Amd321** [comment]
> ~Did you have any erorr on the web console ?~ Nevermind i see the error... try out 0.13.5

The toggle for "VE + WE" works again, and you can also toggle the equip of bags again, however, now bags with "Weightless Unequipped" don't reduce weight when unequipped anymore and the 'Encumbered' active effect isn't removed. (Basically, the whole point of the original bug report)

**Comment by p4535992** [comment]
"_"Weightless Unequipped" don't reduce weight when unequipped_" is working like expected, must be something on your side https://i.imgur.com/Fo6SB9U.gif.

![img](https://i.imgur.com/Fo6SB9U.gif)

can you click F12 and see if there is some error on the web console ?

**Comment by Amd321** [comment]
Nothing on my side. No errors. I'm only using the required modules which are all up to date. Also, don't see you testing with the encumbered effect so that might be a thing. Should also be removing encumbered or adding encumbered active effect.

**Comment by Amd321** [comment]
![1](https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/assets/77754673/301aee66-5009-410e-9acb-bec320685573)
![2](https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/assets/77754673/d51941ac-210d-40ba-b119-50246b606e1d)
As you can see it does not function with "Variant Encumbrance + Weight" is enabled on a sheet. However it does function when they are disabled, which defeats the whole purpose as it doesn't work with DAE to add or remove encumbrance.

**Comment by p4535992** [comment]
Sorry completely forgot about this, cannot replicate on my actors can you pass to me the actor json file ? (rename with suffix .txt for upload on github) @Amd321
