### ISSUE TITLE
[BUG] Error upon opening the character sheet (bulk)

### ISSUE THREAD

**Issue by MaxorCore** [p4535992/foundryvtt-variant-encumbrance-dnd5e#24]
1. Open Charactersheet
2. See error

Any Idea of what is wrong here? I tried every option but i doesnt seem to go away. Im using the bulk system and only when active it writes the errors.

Also anything i try the second encumbrance bar never goes away.

Im using the default charactersheet

![image](https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/assets/130377716/ac344c75-1c14-48a1-ab96-e8d306f6d849)

[localhost-1695951615442.log](https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/files/12755204/localhost-1695951615442.log)

![image](https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/assets/130377716/9d32f55a-3eb5-4c15-997f-ca486e852a3b)

**Comment by p4535992** [comment]
are you using some custom css ?also always specify module version and system version please.

**Comment by p4535992** [comment]
Possibly connected to https://discord.com/channels/170995199584108546/722566083499786352/1175164507660746822

**Comment by p4535992** [comment]
After all this time should be fixed on version 0.14.0.
