### ISSUE TITLE
[BUG][Auto Assigned] Module incompatibility with Chris Premade (to verify)

### ISSUE THREAD

**Issue by p4535992** [p4535992/foundryvtt-variant-encumbrance-dnd5e#27]
Having variant Encumbrance + Midi will prevent Chri's Premades BG3 Weapon Actions from being applied  to Players Character

**Comment by KellethDregar** [comment]
Hey @p4535992 just checking is there any update for this bug?

**Comment by p4535992** [comment]
nope sorry got involved with other modules and this is falling behind my schedule .

**Comment by KellethDregar** [comment]
Ah ok, thanks for the follow up!

**Comment by p4535992** [comment]
@KellethDregar what item in the specific did you test ? i have some issue to replicate the bug.

**Comment by KellethDregar** [comment]
@p4535992 I tested with the SRD Greataxe and Longbow. I've tested equipping and switching between them. Doesn't work when this module is enabled but when its disabled you can equip one and it'll add the abilities, then unequip where it'll remove them and equip the other and it'll add them for that weapon.

Also when I had this module disabled and equip a weapon the abilities appear, then when I re-enable this module they just stay there even if the weapon is unequipped or changed. So seems whatever is causing the abilities to populate or delete just stops whenever the Variant Encumberance module is on.

**Comment by KellethDregar** [comment]
Some videos to show how it looks.

Without Variant Encumberance:
https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/assets/79947702/ae84f7b7-e847-40d1-8f83-f63eff172028

With Variant Encumberance:
https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/assets/79947702/eec9156c-106b-4f36-a1b6-512c993d603e

**Comment by p4535992** [comment]
a ok sorry i didn't understand the issue, can you pass me the json of the video actor so i text directly with that, remember to rename the file from ".json" to ".txt" to upload it to github

**Comment by KellethDregar** [comment]
@p4535992 Sure thing, here is the json for the actor.

[fvtt-Actor-test-bg3-weapon-K16JQt5D4yi0vvJJ.txt](https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/files/14010793/fvtt-Actor-test-bg3-weapon-K16JQt5D4yi0vvJJ.txt)

**Comment by p4535992** [comment]
Should be solved
