### ISSUE TITLE
proficient equipped item weight multiplier doesn't seem to do anything

### ISSUE THREAD

**Issue by pumpkin1972** [p4535992/foundryvtt-variant-encumbrance-dnd5e#28]
I haven't raised this as a bug as this could be user error, but i cant get the Proficient equipped item weight multiplier to do anything.

behaviour -
Unequipped Item weight multiplier is 1
Equipped item weight multiplier is 1
Proficient equipped Item Weight multiplier is 0

Equipping or unequipping a proficient weapon does not change the weight calculated.
If equipped item weight multiplier is set to 0, then equipping/.unequipping a weapon does change weight calculated but then the setting applies to ALL items equipped/not equipped, not just weapons.

I have proficient armour as 0 weight using the Do Not apply weight for equipped armour, and that works, but is there a valid set up to have 0 weight for equipped proficient weapons but other equipped items still have full weight?

**Comment by pumpkin1972** [comment]
V11.315 of foundry
V2.4.1 Dnd5e
V0.13.9 of Variant encumbrance+midi

**Comment by p4535992** [comment]
so just for cover all use case you need these additional settings:

- Do Not apply weight for proficient armour (or maybe a specific multiplier)
- Do Not apply weight for equipped weapon (or maybe a specific multiplier)
- Do Not apply weight for proficient weapon (or maybe a specific multiplier)

or something like that right ?

**Comment by pumpkin1972** [comment]
I guess to cover all bases, yes. 
I was trying to use the existing settings so that “proficient equipped” weapons has no weight, but it seems that the “equipped item” multiplier overrides it.
If I wanted to fine tune the house rule, I’d want equipped armour to be 0 weight (you have this already), you might want unequipped armour to have 0 weight too as an option (for players who aren’t sleeping in armour but don’t want to take it off their sheet, etc), then options for equipped weapons to be 0  weight, and possibly proficient items to be 0 weight, whether equipped or not?

**Comment by p4535992** [comment]
Add some new module settings for cover the equipped and the proficient use cases on 0.14.0

_I was trying to use the existing settings so that “proficient equipped” weapons has no weight, but it seems that the “equipped item” multiplier overrides it._ 

Seem to be solved on 0.14.0 i haven't replicate the issue

_unequipped armour to have 0 weight too as an option (for players who aren’t sleeping in armour but don’t want to take it off their sheet, etc),_

Do not make any sense if the armor is unequipped is just weight, i add on 0.14.0 some hooks you can use for apply your own rule

_and possibly proficient items to be 0 weight, whether equipped or not?_ 

Do not make any sense the weapon or armor must be equipped to be proficient , i add on 0.14.0 some hooks you can use for apply your own rule.

**Comment by pumpkin1972** [comment]
thanks for the additional settings, I can't get the behaviour i want but not sure if it's a settings combination issue?
Can you module bet set as follows?

All regular items have standard weight (x1) 
non proficient armour whether carried OR equipped have standard weight (x1)
proficient armour (not equipped) but carried, has standard weight (x1)
proficient, equipped armour have weight 0
non proficient weapons whether carried OR equipped have standard weight (x1)
proficient weapons (not equipped) but carried, has standard weight (x1)
proficient, equipped weapons have weight 0

It seems like the settings should allow for this but I can't get it to work.
thanks
EDIT: I have run this module V0.14.1 with only necessary modules and all weapons and armour have proficient = false in debug mode regardless of the setting of the weapon. The proficiency setting of the armour/weapon is not being passed through or picked up correctly by the module

EDIT 2: I think the DnD system always leaves the item.system.proficient setting to be null regardless of proficiency (which is the data point you are using to determine proficiency.
The DnD system actually uses item.system.prof.multiplier (i think?) to register proficiency
