### ISSUE TITLE
[BUG] Settings Scaling in V10

### ISSUE THREAD

**Issue by V3rotti** [p4535992/foundryvtt-variant-encumbrance-dnd5e#3]
**Module Version:** v0.11.6

**Expected behavior**
Settings displayed as standard

**Screenshots**
![image](https://user-images.githubusercontent.com/56869989/195598933-b18d375d-ba0f-4b2a-a6a7-77e69f8c19ea.png)

**Browser:**
 - 

**Foundry Version:** V10

**Game System:** dnd5e

**Additional context**
minor scaling of the settings windows fixes this error.

**Comment by shecrio** [comment]
came here to comment the same thing. I know you have a lot of projects so this ones definitely low priority because like they mentioned if you drag the window to be maybe 3 pixels wider the problem is fixed.

**Comment by p4535992** [comment]
This is a issue with foundryvtt, should be solved with the next patch release ?
https://github.com/foundryvtt/foundryvtt/issues/8175
