### ISSUE TITLE
[BUG] Can't add new items with to sheets

### ISSUE THREAD

**Issue by NdranC** [p4535992/foundryvtt-variant-encumbrance-dnd5e#31]
**Module Version:** v0.14.3

**Describe the bug**
When I try to add any item to the inventory of both pc or npc character sheets it doesn't work and it outputs this error to console. This started happening very recently so it could've possibly being introduced by the last update. Spells and other items that assume are not tracked by this mod are able to be added just fine.

**To Reproduce**
1. Create a loot item on the right hand side of the menu. (Item must be of a type that goes into the inventory)
2. Open any character sheet.
3. Drag the item into the character sheet.

**Expected behavior**
No error and item copied over.

**Screenshots**
![Screenshot from 2024-02-02 11-36-06](https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/assets/27837113/c180edee-4233-4167-93a2-dd5362c008dd)

**Browser:**
Firefox 122.0

**Foundry Version:** 
11.315

**Game System:** 
DnD 5e 2.4.1

**Comment by p4535992** [comment]
should be fixed (or at least patched ) on 0.14.7

**Comment by NdranC** [comment]
It seems that way. Thank you.
