### ISSUE TITLE
[BUG?] Red text on the item description

### ISSUE THREAD

**Issue by NdranC** [p4535992/foundryvtt-variant-encumbrance-dnd5e#33]
![Screenshot from 2024-02-03 00-18-20](https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/assets/27837113/f99461f5-e5c7-4b97-bfcf-6dcda9629668)

I started noticing this red text on the bottom left of all item boxes. This seems to be a debug feature but I checked all the settings I can't find a way to turn it off. Is this a bug or am I missing something?

**Comment by p4535992** [comment]
By default is visible only for gm .
Is a read-only value that should help you understand how much the individual item weights to see if the settings you have set are correct do you want me to remove it for GMs as well ?

**Comment by NdranC** [comment]
A setting would be nice. It's probably something I would check once or twice then disable.

**Comment by p4535992** [comment]
For not to add another settings for this a tooltip can be a acceptable solution for this ?

[Imgur](https://i.imgur.com/mMiUGmQ.gifv)
![Imgur](https://i.imgur.com/mMiUGmQ.gif)

**Comment by NdranC** [comment]
The tooltip looks fine. Thank you very much.
