### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Zarhog** [p4535992/foundryvtt-variant-encumbrance-dnd5e#35]
![image](https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/assets/76391362/3832dd2b-1d91-4f74-a7dc-1b944934e1c5)
![image](https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/assets/76391362/4d70c78c-0c50-472f-9449-0136fcc1742b)
![image](https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/assets/76391362/e499511f-9de3-441c-8199-9f688b4358fa)

waight isnt being calculated properly, calculation is ignoring Quantity for some reason

**Comment by p4535992** [comment]
Sorry can you export the actor and pass to me ? i need to check something...

**Comment by p4535992** [comment]
@Zarhog sorry for the delay can you pass to me the actor ?

**Comment by Zarhog** [comment]
Apoligies P4535992, the issue had resolved its self before i could

**Comment by Zarhog** [comment]
it would appear that this is some sort of loading ordering issue reguaring the test for Quantity perhaps.
