### ISSUE TITLE
Error thrown on reopen of container DND5e

### ISSUE THREAD

**Issue by ChthonicKnight** [p4535992/foundryvtt-variant-encumbrance-dnd5e#36]
**Module Version:** v0.13.5

**Describe the bug**
After opening a container on a character sheet then closing it and trying to open the same container again it throws an error.
![image](https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/assets/21301107/4d739668-ce37-4b2e-bd80-ebb0f3e8da70)

**To Reproduce**
1. Open a character sheet with a container
2. Close the container
3. Attempt to open the same container again.

**Expected behavior**
Should open normally

**Browser:**
Firefox

**Foundry Version:** 
11.315
**Game System:** 
D&D5e-3.1.2

**Comment by p4535992** [comment]
the version seem stucked to a very old one uninstall and reinstall the module the last version is 0.15.5

**Comment by ChthonicKnight** [comment]
Oh yeah that fixed it, not sure why it was stuck on 13.5
