### ISSUE TITLE
[Request] Portuguese-BR Language

### ISSUE THREAD

**Issue by Andersants** [p4535992/foundryvtt-variant-encumbrance-dnd5e#39]
Dear, good evening.
I've taken the liberty of translating the Module into pt-BR.
After adding the language file and making the necessary changes to "module.json" the module worked as expected when the pt-BR language is selected, but it presents errors in the weight effects when it is in "en". If you can check and find the reason, I've left the file here so that it can be included in the module.
Thank you.

[pt-BR.json](https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/files/15341675/pt-BR.json)
[module.json](https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/files/15341680/module.json)

**Comment by p4535992** [comment]
Ty i will add on the next release
