### ISSUE TITLE
Tie creature bulk to STR score

### ISSUE THREAD

**Issue by weepingminotaur** [p4535992/foundryvtt-variant-encumbrance-dnd5e#4]
Currently, there is no way to adjust the maximum bulk for a creature, which is tied to size. Would appreciate being able to tie bulk to a creature's Strength score (not modifier).

**Comment by p4535992** [comment]
The code (for bulk calculation) is bounded to the str mod (and the size of course).

https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/blob/3b8436d385021a469b3f38450d8a79cdf8f79902/src/scripts/VariantEncumbranceBulkImpl.ts#L586

did you have some suggestion for a better behaviour ?

**Comment by weepingminotaur** [comment]
I was asking about being able to tie it purely to STR score, not to STR modifier or size.

**Comment by p4535992** [comment]
ok is very simple to integrate.
Some people use DAE for accomplish the same thing if you can find that useful.
For your use case is enough to replace the `actorEntity.system.abilities.str.mod` with `actorEntity.system.abilities.str.value` ?

**Comment by weepingminotaur** [comment]
OK, I'll try that -- thanks for the suggestion!

**Comment by p4535992** [comment]
version 0.11.7 has this module setting now
