### ISSUE TITLE
[BUG] Not working properly in 3.x

### ISSUE THREAD

**Issue by Nedrapter** [p4535992/foundryvtt-variant-encumbrance-dnd5e#40]
**Module Version:** v0.0.0
0.15.6
**Before open any issue**

**Describe the bug**
After upgrading to dnd5e 3.X the module seems to glitch the encumbrance bar and not work at all.

**To Reproduce**
Activate module in dnd5e 3.X

**Screenshots**
Modules active 
![image](https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/assets/74311190/c3c4b412-f68d-4688-a2db-80982a3179bb)
How it looks 
![image](https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/assets/74311190/c6115323-2dbb-4dfd-a225-2a9869d8af38)

There are no 3 scales anymore and once this bar reaches the maximum (which shows no numbers) it applies these conditons
![image](https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/assets/74311190/d91650d2-fff6-48f7-967f-11bf0dfc779c)

**Browser:**
Opera, Chrome
**Foundry Version:** 
11.315
**Game System:** 
dnd5e 3.1.2
**Additional context**
I see the core rules have a Variant Encumbrance mode you can turn on, but there you cant set up the limits and the default ones are ridiculous or wrong...

**Comment by p4535992** [comment]
Closed because already asked here https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/issues/37

**Comment by p4535992** [comment]
There is also a open commission on the league server if  you want to give something for fix this behaviour
