### ISSUE TITLE
[BUG] Conflict with Hero Creation Tool Module

### ISSUE THREAD

**Issue by Dialectikal** [p4535992/foundryvtt-variant-encumbrance-dnd5e#5]
Module Version: v0.10.3
Browser: Chrome
Foundry Version: 9.269
Game System: DnD5e 1.6.3

It seems there is an issue with editing items on any actor that was created using the Hero Creation Tool module.
If I create an actor normally, dragging items to the character sheet, there is no issue. But any items that were added as part of the Hero Creation Tool can't be edited or removed as long as the Variant Encumbrance module is activated.

If I try with the "Disable the socketLib feature..." option checked, I get the following:
![image](https://user-images.githubusercontent.com/31572084/196861628-ae1f70f4-6ba3-477e-b0a3-eaed633c310a.png)

Otherwise, I get the following error:
![image](https://user-images.githubusercontent.com/31572084/196861708-e0fb988e-2917-41bf-b7b1-1ab5f8489b3c.png)

This only occurs with the Variant Encumbrance module activated. The dependencies don't cause any issues. I have used Find the Culprit as well, to eliminate the possibility of other conflicts.

**Comment by p4535992** [comment]
I am really sorry, but I have so little time to devote to my many modules that I have decided not to support any more requests inherent to fvtt  9. It still seems to be a poor handling of effect checking on my side. If the error persists in 10 as well let me know.
