### ISSUE TITLE
[BUG][Compatibility Module Inventory+] "Enable/Disable feature for applying Active effects for specific actors" Deselecting this option breaks the module. Bulk is no longer tracked, and it breaks some of the options for Inventory+. 

### ISSUE THREAD

**Issue by Orionox** [p4535992/foundryvtt-variant-encumbrance-dnd5e#6]
**Module Version:** v0.11.7

**Before open any issue**
Inventory+ "Ignore Weight Test."
![Screenshot 2022-11-06 082405](https://user-images.githubusercontent.com/20059838/200179417-5386f4d2-ee67-46a6-9403-70fbba6e9c54.jpg)
Inventory+ "Ignore Bulk Test."
![Screenshot 2022-11-06 082519](https://user-images.githubusercontent.com/20059838/200179479-2e202d4e-654d-4f5f-a1b6-8d8d83d2ae13.jpg)
Bulk tracking Test
![Screenshot 2022-11-06 082804](https://user-images.githubusercontent.com/20059838/200179583-a0b09ff1-21a0-4cc9-b9e9-a235a72a97d3.jpg)

**Describe the bug**
While the option "Enable/Disable feature for applying Active effects for specific actors" is deselected bulk is no longer tracked properly. Additionally, both the ignore weight and ignore bulk options from Inventory+ stop working. Reselecting that option restores bulk tracking and inventory+ functionality. 

**To Reproduce**
1. Open Configure Game setting
2. Go to the variant encumbrance options. 
3. Deselect "Enable/Disable feature for applying Active effects for specific actors"
![Screenshot 2022-11-06 083154](https://user-images.githubusercontent.com/20059838/200179763-ef53bb09-6bb0-4431-9c53-adcf247b7b8c.jpg)
4. Open character sheet and bulk will no longer be properly tracked and the inventory+ options will have stopped working.
5.  Re-Enabling the "Enable/Disable feature for applying Active effects for specific actors" option restores functionality. 

**Expected behavior**
The "Enable/Disable feature for applying Active effects for specific actors" option is for people who want to or need to change how encumbrance is tracked on a player-by-player basis.  Since I do not need that functionality, and since the "Enable/Disable feature for applying Active effects for specific actors" affects performance I want to disable it. With it disabled I'd expect the variant encumbrance to still work properly. 

**Foundry Version:**
V10.288
**Game System:** 
5e V2.0.3
**Additional context**
 If you need additional screenshots of the debug WITH the "Enable/Disable feature for applying Active effects for specific actors" option activated I can provide that as well. 
Lastly, do you have a tip jar or something? you do such a phenomenal job with support I'd like to toss you something!

**Comment by p4535992** [comment]
Can you pass to me the actor ? (rename with .txt the .json file for github limitation>)

**Comment by Orionox** [comment]
It happens with all my actors.

**Comment by Orionox** [comment]
[fvtt-Actor-luke-wydusathat.txt](https://github.com/p4535992/foundryvtt-variant-encumbrance-dnd5e/files/9980971/fvtt-Actor-luke-wydusathat.txt)

**Comment by p4535992** [comment]
ty orionox i have already see the problem i will try to fix this week end
