### ISSUE TITLE
[BUG] Ability skill with italian translation lost the charachteristic to use

### ISSUE THREAD

**Issue by alexdiste** [p4535992/foundryvtt-variant-encumbrance-dnd5e#7]
**Module Version:** v0.11.7

**Before open any issue**

1) Enable the module setting _"Enable debugging"_
2) Click F12 go to the _console_ tab 
3) make the test you want and replicate the error
4) Go to the tab console open on point 2) and just right click and click 'Save as' and 'Save' or send a screenshot of the exception on the console.
5) Attach the text file on the github issue with all the logs related tot he module, or send a screenshot of the messages on the console.

**Describe the bug**
There is a strange combination with Dnd5e Italian translation module.
If I enable Dnd5e Italian transalation the ability check lose the charachteristic. For example Acrobatic skill that is based on DEXterity (destrezza) meanwhile seems based on Forza (STR) because is the first of list.
Only skills based on INT (intelligence - intelligenza) are good because INT is valid for both languages but all other skill lose the charachteristic .

**To Reproduce**
Install Dnd 5e Italian transalation
Install Varian encumebrance
Active them and you will find the issue

**Screenshots**
![image](https://user-images.githubusercontent.com/82694721/200641709-761198e5-6683-408a-891f-e5ed80568865.png)
![image](https://user-images.githubusercontent.com/82694721/200642662-06a6d002-b8d9-425f-a884-503dd7db8bba.png)
![image](https://user-images.githubusercontent.com/82694721/200642540-32270fc5-69de-45f5-b73c-3e8c035f26ad.png)

**Browser:**
 Edge

**Foundry Version:** 
10.288

**Game System:** 
Dnd5e

**Additional context**
Add any other context (like other modules installed) about the problem here.

**Comment by p4535992** [comment]
Can you confirm all the checkboxes of the module "Active effect manager" are set to false ? All checkbox ogf the module "Active effect manager" must be unchecked.

**Comment by p4535992** [comment]
Should be solved with 0.11.8
