### ISSUE TITLE
[Request] Custom Equipped Armor Weight Multiplier

### ISSUE THREAD

**Issue by arlosmolten** [p4535992/foundryvtt-variant-encumbrance-dnd5e#9]
This is mostly an upgrade from an existing feature. Change the _"Feature: Do not apply weight for equipped armor item"_ for _"Feature: Equipped Armor Weight Multiplier"_, and let input a number, so we could change specifically only equipped armor, instead of being a 0 or 1 option.

Reasoning: As is kinda annoying to equip and unequip weapons in character sheet, letting all weapons be equipped is better for the flux of the game, but the features for equipped and proficient multipliers can affect too many items. For a simple rule change, we could get a multiplier just for equipped armor, one of the most common and heavier items on adventurers, and this way, the old rule can be used too, just with a zero value.

**Comment by p4535992** [comment]
~~You need this only for armor or for any item equipped ?~~ Nevermind thata setting already exists so i guess you need this only for armor

**Comment by arlosmolten** [comment]
Yes. It is a request for only equipped armor multiplier.

**Comment by p4535992** [comment]
Added on v0.11.11
